In [1]:
import pandas as pd

data_business = {
    "business_id": [
        "G5ERFWvPfHy7IDAUYlWL2A", "0jDvRJS-z9zdMgOUXgr6rA", "6HmDqeNNZtHMK0t2glF_gg",
        "pbt3SBcEmxCfZPdnmU9tNA", "CX8pfLn7Bk9o2-8yDMp_2w", "yzAB_pRwk8FJl3aILiiySA",
        "p8keQs0xw0TzP0JjYPiZPQ", "lbxfIXUNUdSRO2t7z2PxPA", "xxCrRqqICzQyR0Q-iqCrNw",
        "WdQP8kl9SzcOdubWz0Rs5g", "g6KfICYxIFoXnz7KHzQDpw", "Lhtl6hEr4BaAR4aA3RQDNQ",
        "6FmJM2SYWoUv_DC8FA7hpg", "JJWQxF7ljXKVvCxn3ug-CA", "3rptIkeGoVRdPF4v6omLOg",
        "JGvyv9jO8kfEnf4WtnpzfQ", "dRb2Xq8jorJV6tDCgmaQUg", "r7MJN_4aJdNP_mx6u_4czQ",
        "_QEwts97jzVcvfVo4qveFA", "-M9S1wlZTvv6T9EOo5X2Yw"
    ],
    "name": [
        "All Colors Mobile Bumper Repair", "Sunfare", "Dry Clean Vegas", "The Cuyahoga Room", 
        "The UPS Store", "CenturyLink", "The Enfield Fox", "Budget Car Rental", "Subway", 
        "Red Beard Bodywork And Structural Integration", "Chase Bank", "Dairy Queen", 
        "1st Choice Storage Solutions", "Applebee's Neighborhood Grill & Bar", "Sunless Boutique", 
        "Dairy Queen", "Papa John's Pizza", "Red Roof Inn", "Integrated Pain Specialists", 
        "Grandeur Palace"
    ],
    "neighborhood": [
        "", "", "Southeast", "", "", "Spring Valley", "", "", "Plaza Midwood", "Capitol",
        "", "", "Southeast", "", "The Lakes", "", "", "", "Spring Valley", "Scarborough"
    ],
    "address": [
        "7137 N 28th Ave", "811 W Deer Valley Rd", "2550 Windmill Ln, Ste 100", 
        "740 Munroe Falls Ave", "4815 E Carefree Hwy, Ste 108", "4850 S Fort Apache Rd, Ste 100", 
        "285 Enfield Place", "7125 E Shea Blvd, Ste 101", "1300 The Plz", 
        "301 S Bedford St", "705 S Green Valley Pkwy", "475 W Craig Rd", 
        "6360 S Pecos Rd, Ste 14", "13756 W Bell Rd", "9921 Mahogany Grove Ln", 
        "13623 W Camino Del Sol", "703 E Bell Rd", "7400 W Boston St", 
        "9333 W Sunset Rd, Ste A", "2301 Brimley Road, Unit 128"
    ],
    "city": [
        "Phoenix", "Phoenix", "Las Vegas", "Cuyahoga Falls", "Cave Creek", "Las Vegas", 
        "Mississauga", "Scottsdale", "Charlotte", "Madison", "Henderson", "North Las Vegas", 
        "Las Vegas", "Surprise", "Las Vegas", "Sun City West", "Phoenix", "Chandler", 
        "Las Vegas", "Toronto"
    ],
    "state": [
        "AZ", "AZ", "NV", "OH", "AZ", "NV", "ON", "AZ", "NC", "WI", "NV", "NV", 
        "NV", "AZ", "NV", "AZ", "AZ", "AZ", "NV", "ON"
    ],
    "postal_code": [
        "85051", "85027", "89123", "44221", "85331", "89147", "L5B 3Y6", "85254", "28205", 
        "53703", "89052", "89032", "89120", "85374", "89117", "85375", "85022", "85226", 
        "89148", "M1S 5B8"
    ],
    "latitude": [
        33.45, 33.68, 36.04, 41.14, 33.8, 36.1, 43.59, 33.58, 35.22, 43.07, 
        36, 36.24, 36.07, 33.64, 36.14, 33.65, 33.64, 33.3, 36.07, 43.8
    ],
    "longitude": [
        -112.07, -112.08, -115.12, -81.47, -111.98, -115.3, -79.64, -111.93, -80.81, 
        -89.39, -115.08, -115.15, -115.1, -112.36, -115.31, -112.36, -112.07, -111.97, 
        -115.3, -79.27
    ],
    "stars": [
        1, 5, 1, 1, 1.5, 1.5, 1.5, 2, 2, 5, 2, 2, 2, 2.5, 5, 2.5, 5, 2.5, 2.5, 2.5
    ],
    "review_count": [
        4, 27, 4, 3, 5, 35, 3, 6, 13, 10, 6, 57, 7, 56, 20, 16, 3, 3, 8, 46
    ],
    "is_open": [
        1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1
    ],
    "categories": [
        "Auto Detailing;Automotive", "Personal Chefs;Food;Gluten-Free;Food Delivery Services;Event Planning & Services;Restaurants",
        "Dry Cleaning & Laundry;Laundry Services;Local Services;Dry Cleaning", 
        "Wedding Planning;Caterers;Event Planning & Services;Venues & Event Spaces",
        "Notaries;Printing Services;Local Services;Shipping Centers",
        "Home Services;Television Service Providers;Professional Services;Internet Service Providers;Utilities",
        "Bars;Restaurants;Pubs;British;Nightlife", "Hotels & Travel;Car Rental", 
        "Fast Food;Sandwiches;Restaurants", 
        "Rolfing;Health & Medical;Beauty & Spas;Massage", 
        "Financial Services;Banks & Credit Unions", "Food;Ice Cream & Frozen Yogurt", 
        "Shopping;Home & Garden;Home Services;Cabinetry;Furniture Stores", 
        "Burgers;Bars;American (Traditional);Nightlife;Restaurants;Sports Bars;Steakhouses", 
        "Hair Removal;Beauty & Spas;Skin Care;Tanning;Spray Tanning;Hair Salons", 
        "Restaurants;Ice Cream & Frozen Yogurt;Fast Food;Food", "Restaurants;Pizza", 
        "Hotels;Hotels & Travel;Event Planning & Services", 
        "Health & Medical;Physical Therapy", "Restaurants;Seafood;Chinese;Dim Sum"
    ]
}

df_business = pd.DataFrame(data_business)

In [2]:
df_business.head()

,business_id,name,neighborhood,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,categories
0,G5ERFWvPfHy7IDAUYlWL2A,All Colors Mobile Bumper Repair,,7137 N 28th Ave,Phoenix,AZ,85051,33.45,-112.07,1.0,4,1,Auto Detailing;Automotive
1,0jDvRJS-z9zdMgOUXgr6rA,Sunfare,,811 W Deer Valley Rd,Phoenix,AZ,85027,33.68,-112.08,5.0,27,1,Personal Chefs;Food;Gluten-Free;Food Delivery ...
2,6HmDqeNNZtHMK0t2glF_gg,Dry Clean Vegas,Southeast,"2550 Windmill Ln, Ste 100",Las Vegas,NV,89123,36.04,-115.12,1.0,4,1,Dry Cleaning & Laundry;Laundry Services;Local ...
3,pbt3SBcEmxCfZPdnmU9tNA,The Cuyahoga Room,,740 Munroe Falls Ave,Cuyahoga Falls,OH,44221,41.14,-81.47,1.0,3,0,Wedding Planning;Caterers;Event Planning & Ser...
4,CX8pfLn7Bk9o2-8yDMp_2w,The UPS Store,,"4815 E Carefree Hwy, Ste 108",Cave Creek,AZ,85331,33.80,-111.98,1.5,5,1,Notaries;Printing Services;Local Services;Ship...

Find the top 5 states with the most 5 star businesses. Output the state name along with the number of 5-star businesses and order records by the number of 5-star businesses in descending order. In case there are ties in the number of businesses, return all the unique states. If two states have the same result, sort them in alphabetical order.

In [17]:
df_business[df_business['stars'] == 5].groupby('state', as_index = False)['business_id'].count().rename(columns = {'business_id': 'n_businesses'}).sort_values(by = ['n_businesses','state'], ascending = [False,True ]).nlargest(5, 'n_businesses', 'all')

  state  n_businesses
0    AZ             2
1    NV             1
2    WI             1

In [ ]:
# sql
# rank row-wise
# dense rank
# rank
with cte as (
select state, count(business_id) as n_businesses
from yelp_business
where start = 5
group by state
).
cte2 as (
select * , rank() over(order by n_businesses desc) as rnk
from cte )

select state, n_businesses
from cte2
where rnk <=5
order by n_businesses desc, state ## order by n_business, when there is a tie then alphabetical order by state